# Copyright 2020 the V8 project authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: Update V8 Tools

on:
  push:
    branches:
      - main
  schedule:
    # Rebuild tools every hour.
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy V8 Tools
    runs-on: ubuntu-latest
    container:
      image: docker://python:3.7-alpine
    steps:
      - name: Install Dependencies
        run: apk add git openssh-client rsync tar zstd npm
      - name: Checkout main Branch
        uses: actions/checkout@v2
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gen
      - name: Build V8 Tools
        run: python3 -u update.py
      - name: Prevent auto-deploy
        run: touch gen/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4.2.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: gen
          git-config-name: V8 Tools Updater
          git-config-email: cbruni@chromium.org
